# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode = false
    windows_leader = ''
    windows_smartclose = ''
    disabled_plugins = ['vim-smoothie', 'vim-nim']
    bootstrap_before = 'myconfig#before'
    bootstrap_after = 'myconfig#after'

[[layers]]
  name = 'core'
  enable_filetree_gitstatus = true

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 20

[[layers]]
  name = 'lang#python'
  merged = false

[[layers]]
  name = 'lang#nim'
  merged = false

[[layers]]
  name = 'git'
  git_plugin = 'fugitive'

[[custom_plugins]]
  repo = "wsdjeg/vim-nim"
  merged = false

[[layers]]
  name = 'fzf'
  merged = false

[[custom_plugins]]
  repo = 'junegunn/fzf.vim'
  merged = false

[[custom_plugins]]
  repo = 'junegunn/fzf'
  merged = false
